#### **Agasse Station**

```{r message=FALSE, warning=FALSE, include=FALSE}
# Creation of time series
Agasse <- as_tsibble(Agasse)
weekday <- weekdays(Agasse$date)
Agasse$weekday <- weekday # Get the weekday values
Agasse$time <- as.POSIXct(Agasse$date, format = "%H:%M:%S %p")
Agasse$time <- as.numeric(Agasse$date) #convert date values to numeric
as.numeric(Agasse$time)

agasse <- Agasse %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
agasse$minutes <- as.numeric(as.character(agasse$minutes))/60 # transform to minutes

# Filter the data by time difference of 10 min
agasse <- agasse %>% filter(minutes == 10) %>%
  select(-time,-name) %>%
  relocate(date, .before = Bike)

# Identifying the gaps on the ts and fill them
agasse.gaps <- has_gaps(agasse)
agasse.gaps <- scan_gaps(agasse)
agasse <- agasse %>% 
  fill_gaps(.full = TRUE) 

# Replace NA's values as previous row 
agasse_ts <- agasse %>%
  fill(Bike, `E-Bike`, Capacity, weekday, minutes)
scan_gaps(agasse_ts) # no missing values

#  convert our data frame from wide to long format.
agasse <- agasse_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)
```

```{r, message=FALSE, warning=FALSE}
### Usage for Wednesdays - Bikes ###
agasse_wednesday <- agasse %>%
  filter(weekday == "Wednesday") 
lubridate::day(agasse_wednesday$date) <- 16
lubridate::month(agasse_wednesday$date) <- 04
agasse_wednesday <- agasse_wednesday %>%
  group_by(date, Types) %>%
  summarise(Number = median(Number)) %>%
  as_tsibble(key = Types) %>%
  mutate(weekday = "Wednesday")
agasse_wednesday$Number <- ceiling(agasse_wednesday$Number)

agasse_wednesday %>% 
  select(-weekday) %>%
  autoplot(Number) +
  labs(x = "Time [10']",
       y = "Number") + 
  ggtitle("Wednesdays Usage(Mdn) - Agasse")

# Time series for Wednesdays - Bike
agasse_wednesdays_bike <- agasse %>% 
  filter(Types == "Bike" ) %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p1 <- agasse_wednesdays_bike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bike - agasse") +
  labs(x = "Time [10']",
       y = "Number")

# Time series for Wednesdays - E-Bike
agasse_wednesdays_ebike <- agasse %>% 
  filter(Types == "E-Bike") %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p2 <- agasse_wednesdays_ebike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - E-Bike - agasse") +
  labs(x = "Time [10']",
       y = "Number")
p1 / p2
```


```{r message=FALSE, warning=FALSE}
# Is it white noise for the bike at the agasse? 
p1 <- agasse_wednesdays_bike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
agasse_wednesdays_bike %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.

# Is our time series stationary or not? #We confirm it with the test
agasse_wednesdays_ebike %>% features(Number, unitroot_kpss) # No p-value < 0.05

# Is it white noise for the bike at the agasse?
p2 <- agasse_wednesdays_ebike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("E-Bike")
p1 / p2
```
