#### **UNIL/UNIGE Bramois Station**

```{r message=FALSE, warning=FALSE, include=FALSE}
# Creation of time series
Bramois <- as_tsibble(Bramois)
weekday <- weekdays(Bramois$date)
Bramois$weekday <- weekday # Get the weekday values
Bramois$time <- as.POSIXct(Bramois$date, format = "%H:%M:%S %p")
Bramois$time <- as.numeric(Bramois$date) #convert date values to numeric
as.numeric(Bramois$time)

bramois <- Bramois %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
bramois$minutes <- as.numeric(as.character(bramois$minutes))/60 # transform to minutes

# Filter the data by time difference of 10 min
bramois <- bramois %>% filter(minutes == 10) %>%
  select(-time,-name) %>%
  relocate(date, .before = Bike)

# Identifying the gaps on the ts and fill them
bramois.gaps <- has_gaps(bramois)
bramois.gaps <- scan_gaps(bramois)
bramois <- bramois %>% 
  fill_gaps(.full = TRUE) 


# Replace NA's values as previous row 
bramois_ts <- bramois %>%
  fill(Bike, `E-Bike`, Capacity, weekday, minutes)
scan_gaps(bramois_ts) # no missing values

#  convert our data frame from wide to long format.
bramois <- bramois_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)
```

```{r, message=FALSE, warning=FALSE}
### Usage for Wednesdays - Bikes ###
bramois_wednesday <- bramois %>%
  filter(weekday == "Wednesday") 
lubridate::day(bramois_wednesday$date) <- 16
lubridate::month(bramois_wednesday$date) <- 04
bramois_wednesday <- bramois_wednesday %>%
  group_by(date, Types) %>%
  summarise(Number = median(Number)) %>%
  as_tsibble(key = Types) %>%
  mutate(weekday = "Wednesday")
bramois_wednesday$Number <- ceiling(bramois_wednesday$Number)

bramois_wednesday %>% 
  select(-weekday) %>%
  autoplot(Number) +
  labs(x = "Time [10']",
       y = "Number") + 
  ggtitle("Wednesdays Usage(Mdn) - Bramois")

# Time series for Wednesdays - Bike
bramois_wednesdays_bike <- bramois %>% 
  filter(Types == "Bike" ) %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p1 <- bramois_wednesdays_bike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bike - bramois") +
  labs(x = "Time [10']",
       y = "Number")

# Time series for Wednesdays - E-Bike
bramois_wednesdays_ebike <- bramois %>% 
  filter(Types == "E-Bike") %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p2 <- bramois_wednesdays_ebike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - E-Bike - bramois") +
  labs(x = "Time [10']",
       y = "Number")

p1 / p2
```


```{r message=FALSE, warning=FALSE}
# Is it white noise for the bike at the bramois? 
p1 <- bramois_wednesdays_bike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
bramois_wednesdays_bike %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.

# Is our time series stationary or not? #We confirm it with the test
bramois_wednesdays_ebike %>% features(Number, unitroot_kpss) # No p-value < 0.05

# Is it white noise for the bike at the bramois?
p2 <- bramois_wednesdays_ebike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("E-Bike")
p1 / p2
```