#### **Campus Energypolis Station**

```{r message=FALSE, warning=FALSE, include=FALSE}
# Creation of time series
Campus <- as_tsibble(Campus)
weekday <- weekdays(Campus$date)
Campus$weekday <- weekday # Get the weekday values
Campus$time <- as.POSIXct(Campus$date, format = "%H:%M:%S %p")
Campus$time <- as.numeric(Campus$date) #convert date values to numeric
as.numeric(Campus$time)

campus <- Campus %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
campus$minutes <- as.numeric(as.character(campus$minutes))/60 # transform to minutes

# Filter the data by time difference of 10 min
campus <- campus %>% filter(minutes == 10) %>%
  select(-time,-name) %>%
  relocate(date, .before = Bike)

# Identifying the gaps on the ts and fill them
campus.gaps <- has_gaps(campus)
campus.gaps <- scan_gaps(campus)
campus <- campus %>% 
  fill_gaps(.full = TRUE) 

# Replace NA's values as previous row 
campus_ts <- campus %>%
  fill(Bike, `E-Bike`, Capacity, weekday, minutes)
scan_gaps(campus_ts) # no missing values

#  convert our data frame from wide to long format.
campus <- campus_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)
```

```{r, message=FALSE, warning=FALSE}
### Usage for Wednesdays - Bikes ###
campus_wednesday <- campus %>%
  filter(weekday == "Wednesday") 
lubridate::day(campus_wednesday$date) <- 16
lubridate::month(campus_wednesday$date) <- 04
campus_wednesday <- campus_wednesday %>%
  group_by(date, Types) %>%
  summarise(Number = median(Number)) %>%
  as_tsibble(key = Types) %>%
  mutate(weekday = "Wednesday")
campus_wednesday$Number <- ceiling(campus_wednesday$Number)

campus_wednesday %>% 
  select(-weekday) %>%
  autoplot(Number) +
  labs(x = "Time [10']",
       y = "Number") + 
  ggtitle("Wednesdays Usage(Mdn) - Campus")

# Time series for Wednesdays - Bike
campus_wednesdays_bike <- campus %>% 
  filter(Types == "Bike" ) %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p1 <- campus_wednesdays_bike %>% 
  autoplot() +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bike - Campus") +
  labs(x = "Time [10']",
       y = "Number")

# Time series for Wednesdays - E-Bike
campus_wednesdays_ebike <- campus %>% 
  filter(Types == "E-Bike") %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p2 <- campus_wednesdays_ebike %>% 
  autoplot() +  
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - E-Bike - Campus") +
  labs(x = "Time [10']",
       y = "Number")

p1 / p2
```

```{r message=FALSE, warning=FALSE}
# Is it white noise for the bike at the campus? 
p1 <- campus_wednesdays_bike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
campus_wednesdays_bike %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.

# Is our time series stationary or not? #We confirm it with the test
campus_wednesdays_ebike %>% features(Number, unitroot_kpss) # No p-value < 0.05

# Is it white noise for the bike at the campus?
p2 <- campus_wednesdays_ebike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("E-Bike")
p1 / p2
```

```{r}
# Decomposition of the trend and seasonality for e-bike
dcmp <- campus_wednesdays_ebike %>% 
  model(STL(Number))

components(dcmp) %>% 
  autoplot() +
  xlab("Date [10']")

# Just take the trend
campus_wednesdays_ebike_trend <- dcmp %>% 
  components() %>% 
  as_tsibble() %>% 
  select(t, Types, trend)

campus_wednesdays_ebike_trend %>% 
  autoplot()
```

```{r}
#campus_wednesdays_ebike_cut <- campus_wednesdays_ebike_trend %>% 
#  slice(1:(n() - 288)) 

#campus_wednesdays_ebike_fit <- campus_wednesdays_ebike_cut %>% 
#  model(ETS = ETS(trend),
#        arima = ARIMA(trend))

#campus_wednesdays_ebike_fit %>% forecast(h = 288) %>% #autoplot(campus_wednesdays_ebike_trend) 
```

