## EDA

```{r, echo = FALSE, message = FALSE, warning=FALSE}
source(here::here("scripts/setup.R"))
```

```{r}
# Creation of time series
Bietschhorn <- as_tsibble(Bietschhorn)
Cible <- as_tsibble(Cible)
GSD <- as_tsibble(GSD)
PRP <- as_tsibble(PRP)
Platta <- as_tsibble(Platta)
Planta <- as_tsibble(Planta)
CRR <- as_tsibble(CRR)
Campus <- as_tsibble(Campus)
Scex <- as_tsibble(Scex)
Furet <- as_tsibble(Furet)
Agasse <- as_tsibble(Agasse)
Stade <- as_tsibble(Stade)
GSN <- as_tsibble(GSN)
Stand <- as_tsibble(Stand)
Bramois <- as_tsibble(Bramois)
Sys.setlocale("LC_TIME", "C")
```

### **Data Description**

#### **Blancherie **
```{r echo=FALSE, message=FALSE}
Blancherie <- as_tsibble(Blancherie)
weekday <- weekdays(Blancherie$date)
Blancherie$weekday <- weekday # Get the weekday values
Blancherie$time <- as.POSIXct(Blancherie$date, format = "%H:%M:%S %p")
Blancherie$time <- as.numeric(Blancherie$date) #convert date values to numeric
as.numeric(Blancherie$time)

blancherie <- Blancherie %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
blancherie$minutes <- as.numeric(as.character(blancherie$minutes))/60 # transform to minutes
blancherie$minutes[blancherie$minutes == 0] <- blancherie$minutes[2] 
blancherie_ts <- blancherie %>%
  relocate(date, .before = Bike) %>%
    select(-time,-name)

#  convert our data frame from wide to long format.
blancherie <- blancherie_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)

############### Monday
blancherie_1 <- blancherie_ts %>% 
  filter(weekday == "Monday")
unique(blancherie_1[c("minutes")]) # Identify the unique values of a column
# The value with a diff time of; 120 only have one observation

# Plot Multiple Series On Same Axes for Monday
p1 <- blancherie %>% filter(weekday == "Monday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Monday")

p2 <- blancherie %>% filter(weekday == "Monday") %>%
  filter(minutes == 10) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes")

p3 <- blancherie %>% filter(weekday == "Monday") %>%
  filter(minutes == 60) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[60min]") + ylab("Amount of Bikes")
p1 /(p2 | p3) #needs library patchwork
```

For the minute values that have only one observation, like the observation with 120min, I think we should modify the value as the previous one 


```{r echo=FALSE, message=FALSE}
############### Tuesday
blancherie_2 <- blancherie_ts %>% 
  filter(weekday == "Tuesday")
unique(blancherie_2[c("minutes")]) # Identify the unique values of a column

# Plot Multiple Series On Same Axes for Tuesday
p1 <- blancherie %>% filter(weekday == "Tuesday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Tuesday")

p2 <- blancherie %>% filter(weekday == "Tuesday") %>%
  filter(minutes == 10) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes")

p3 <- blancherie %>% filter(weekday == "Tuesday") %>%
  filter(minutes == 60) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[60min]") + ylab("Amount of Bikes")
p1 /(p2 | p3) #needs library patchwork
```


```{r echo=FALSE, message=FALSE}
############### Wednesday
blancherie_3 <- blancherie_ts %>% 
  filter(weekday == "Wednesday")
unique(blancherie_3[c("minutes")]) # Identify the unique values of a column
# The values with a diff time of; 20,30 and 40 only have one observation

# Plot Multiple Series On Same Axes for Wednesday
p1 <- blancherie %>% filter(weekday == "Wednesday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Wednesday")

p2 <- blancherie %>% filter(weekday == "Wednesday") %>%
  filter(minutes == 10) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes")

p3 <- blancherie %>% filter(weekday == "Wednesday") %>%
  filter(minutes == 60) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[60min]") + ylab("Amount of Bikes")
p1 /(p2 | p3) #needs library patchwork
```
For the minute values that have only one observation, like the observations with 40, 30 & 20min, I think we should modify the value as the previous one on the data

```{r echo=FALSE, message=FALSE}
############### Thursday
blancherie_4 <- blancherie_ts %>% 
  filter(weekday == "Thursday")
unique(blancherie_4[c("minutes")]) # Identify the unique values of a column
# The values with a diff time of; 20,30 and 40 only have one observation

# Plot Multiple Series On Same Axes for Wednesday
blancherie %>% filter(weekday == "Thursday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Thursday")

############### Friday
blancherie_5 <- blancherie_ts %>% 
  filter(weekday == "Friday")
unique(blancherie_5[c("minutes")]) # Identify the unique values of a column
# The values with a diff time of; 20,30 and 40 only have one observation

# Plot Multiple Series On Same Axes for Wednesday
p1 <- blancherie %>% filter(weekday == "Friday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Friday")

p2 <- blancherie %>% filter(weekday == "Friday") %>%
  filter(minutes == 10) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes")

p3 <- blancherie %>% filter(weekday == "Friday") %>%
  filter(minutes == 60) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[60min]") + ylab("Amount of Bikes")
p1 /(p2 | p3) #needs library patchwork
```

```{r echo=FALSE, message=FALSE}
# Same analysis for Bietschhorn on Monday
Bietschhorn <- as_tsibble(Bietschhorn)
weekday <- weekdays(Bietschhorn$date)
Bietschhorn$weekday <- weekday # Get the weekday values
Bietschhorn$time <- as.POSIXct(Bietschhorn$date, format = "%H:%M:%S %p")
Bietschhorn$time <- as.numeric(Bietschhorn$date) #convert date values to numeric
as.numeric(Bietschhorn$time)

bietschhorn <- Bietschhorn %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
bietschhorn$minutes <- as.numeric(as.character(bietschhorn$minutes))/60 # transform to minutes
bietschhorn$minutes[bietschhorn$minutes == 0] <- bietschhorn$minutes[2] 
bietschhorn_ts <- bietschhorn %>%
  relocate(date, .before = Bike) %>%
    select(-time,-name)

#  convert our data frame from wide to long format.
bietschhorn <- bietschhorn_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)

############### Monday
bietschhorn_1 <- bietschhorn_ts %>% 
  filter(weekday == "Monday")
unique(bietschhorn_1[c("minutes")]) # Identify the unique values of a column
# The value with a diff time of; 120 only have one observation

# Plot Multiple Series On Same Axes for Monday
p1 <- bietschhorn %>% filter(weekday == "Monday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Monday")

p2 <- bietschhorn %>% filter(weekday == "Monday") %>%
  filter(minutes == 10) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes")

p3 <- bietschhorn %>% filter(weekday == "Monday") %>%
  filter(minutes == 60) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[60min]") + ylab("Amount of Bikes")
p1 /(p2 | p3) #needs library patchwork
```

```{r echo=FALSE, message=FALSE}
############### Tuesday
bietschhorn_2 <- bietschhorn_ts %>% 
  filter(weekday == "Tuesday")
unique(bietschhorn_2[c("minutes")]) # Identify the unique values of a column

# Plot Multiple Series On Same Axes for Tuesday
p1 <- bietschhorn %>% filter(weekday == "Tuesday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Tuesday")

p2 <- bietschhorn %>% filter(weekday == "Tuesday") %>%
  filter(minutes == 10) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes")

p3 <- bietschhorn %>% filter(weekday == "Tuesday") %>%
  filter(minutes == 60) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[60min]") + ylab("Amount of Bikes")
p1 /(p2 | p3) #needs library patchwork
```

```{r echo=FALSE, message=FALSE}
# Same analysis for Gare de Sion Nord (GSN) on Monday
GSN <- as_tsibble(GSN)
weekday <- weekdays(GSN$date)
GSN$weekday <- weekday # Get the weekday values
GSN$time <- as.POSIXct(GSN$date, format = "%H:%M:%S %p")
GSN$time <- as.numeric(GSN$date) #convert date values to numeric
as.numeric(GSN$time)

gsn <- GSN %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
gsn$minutes <- as.numeric(as.character(gsn$minutes))/60 # transform to minutes
gsn$minutes[gsn$minutes == 0] <- gsn$minutes[2] 
gsn_ts <- gsn %>%
  relocate(date, .before = Bike) %>%
    select(-time,-name)

#  convert our data frame from wide to long format.
gsn <- gsn_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)

############### Monday
gsn_1 <- gsn_ts %>% 
  filter(weekday == "Monday")
unique(gsn_1[c("minutes")]) # Identify the unique values of a column
# The value with a diff time of; 120 only have one observation

# Plot Multiple Series On Same Axes for Monday
p1 <- gsn %>% filter(weekday == "Monday") %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date") + ylab("Amount of Bikes") +
  ggtitle("Frequencies of usage on Monday")

p2 <- gsn %>% filter(weekday == "Monday") %>%
  filter(minutes == 10) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[10min]") + ylab("Amount of Bikes")

p3 <- gsn %>% filter(weekday == "Monday") %>%
  filter(minutes == 60) %>%
  select(-weekday, -minutes) %>%
  autoplot(Number) +
  xlab("Date[60min]") + ylab("Amount of Bikes")
p1 /(p2 | p3) #needs library patchwork
```