## **Forecasts**

```{r}
# Parameters for all forecasts

# The time interval of our time series - the latest one would be 1350
interval = 1295 # interval for all wednesdays
day_forecasted = '2022-05-25'
```

#### **Bietschhorn Station**

```{r}
# Parameters for this station
station <- bietschhorn_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bietschhorn") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike at the bietschhorn? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        ETS = ETS(Number),
        NAIVE = NAIVE(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Bietschhorn") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final <- subset(fc2_chosen, select = .mean)
forecast_final[,2] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Bietschhorn' = '.mean',
         'Bietschhorn - upper' = 'upper')
```

#### **Blancherie Station**

```{r}
# Parameters for this station
station <- blancherie_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Blancherie") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Blancherie") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,3] <- subset(fc2_chosen, select = .mean)
forecast_final[,4] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Blancherie' = '.mean',
         'Blancherie - upper' = 'upper')
```

#### **Agasse Station**

```{r}
# Parameters for this station
station <- agasse_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Agasse") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Agasse") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,5] <- subset(fc2_chosen, select = .mean)
forecast_final[,6] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Agasse' = '.mean',
         'Agasse - upper' = 'upper')
```

#### **Bramois Station**

```{r}
# Parameters for this station
station <- bramois_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bramois") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Bramois") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,7] <- subset(fc2_chosen, select = .mean)
forecast_final[,8] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Bramois' = '.mean',
         'Bramois - upper' = 'upper')
```

#### **Campus Station**

```{r}
# Parameters for this station
station <- campus_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Campus") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Campus") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,9] <- subset(fc2_chosen, select = .mean)
forecast_final[,10] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Campus' = '.mean',
         'Campus - upper' = 'upper')
```

#### **Cible Station**

```{r}
# Parameters for this station
station <- cible_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Cible") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Cible") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,11] <- subset(fc2_chosen, select = .mean)
forecast_final[,12] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Cible' = '.mean',
         'Cible - upper' = 'upper')
```

#### **CRR Station**

```{r}
# Parameters for this station
station <- crr_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - CRR") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - CRR") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,13] <- subset(fc2_chosen, select = .mean)
forecast_final[,14] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('CRR' = '.mean',
         'CRR - upper' = 'upper')
```

#### **Furet Station**

```{r}
# Parameters for this station
station <- furet_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Furet") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Furet") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,15] <- subset(fc2_chosen, select = .mean)
forecast_final[,16] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Furet' = '.mean',
         'Furet - upper' = 'upper')
```

#### **GSD Station**

```{r}
# Parameters for this station
station <- gsd_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - GSD") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - GSD") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,17] <- subset(fc2_chosen, select = .mean)
forecast_final[,18] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('GSD' = '.mean',
         'GSD - upper' = 'upper')
```

#### **GSN Station**

```{r}
# Parameters for this station
station <- gsn_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - GSN") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - GSN") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,19] <- subset(fc2_chosen, select = .mean)
forecast_final[,20] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('GSN' = '.mean',
         'GSN - upper' = 'upper')
```

#### **Planta Station**

```{r}
# Parameters for this station
station <- planta_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Planta") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Planta") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,21] <- subset(fc2_chosen, select = .mean)
forecast_final[,22] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Planta' = '.mean',
         'Planta - upper' = 'upper')
```

#### **Platta Station**

```{r}
# Parameters for this station
station <- platta_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Platta") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Platta") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,23] <- subset(fc2_chosen, select = .mean)
forecast_final[,24] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Platta' = '.mean',
         'BPlatta - upper' = 'upper')
```

#### **PRP Station**

```{r}
# Parameters for this station
station <- prp_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - PRP") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - PRP") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,25] <- subset(fc2_chosen, select = .mean)
forecast_final[,26] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('PRP' = '.mean',
         'PRP - upper' = 'upper')
```

#### **Scex Station**

```{r}
# Parameters for this station
station <- scex_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Scex") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Scex") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,27] <- subset(fc2_chosen, select = .mean)
forecast_final[,28] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Scex' = '.mean',
         'Scex - upper' = 'upper')
```

#### **Stade Station**

```{r}
# Parameters for this station
station <- stade_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Stade") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Stade") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,29] <- subset(fc2_chosen, select = .mean)
forecast_final[,30] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Stade' = '.mean',
         'Stade - upper' = 'upper')
```

#### **Stand Station**

```{r}
# Parameters for this station
station <- stand_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Stand") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r, eval = FALSE}
# Is it white noise for the bike
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Prepare data for the TSLM forecast - joining weather data
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for the forecasted date
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# Build the combination of all the models
fit2 <- tslm_forecast %>% 
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Stand") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

# Save the output
fc2_chosen <- fc2 %>% 
  filter(.model == "Combination")

fc2_upper <- fc2_chosen %>% 
  hilo(level = 90)

fc2_upper <- fc2_upper %>% 
  mutate(upper = fc2_upper$`90%`$upper)

forecast_final[,31] <- subset(fc2_chosen, select = .mean)
forecast_final[,32] <- subset(fc2_upper, select = upper)

forecast_final <- forecast_final %>% 
  rename('Stand' = '.mean',
         'Stand - upper' = 'upper')
```