## **Forecasts**

```{r}
# Parameters for all forecasts

# The time interval of our time series - the latest one would be 1350
interval = 1295 # interval for all wednesdays
day_forecasted = '2022-05-11'
```

#### **Bietschhorn Station**

```{r}
# Parameters for this station
station <- bietschhorn_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bietschhorn") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the bietschhorn? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Bietschhorn
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Bietschhorn") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Bietschhorn' = '.mean')
```


```{r}
######################## Visualization of all the models ############################ 

# Build the combination of all the models
fit2 <- tslm[1:interval_fc,] %>%
  model(ARIMA = ARIMA(Number),
        TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed)) %>%
  mutate(Combination = (ARIMA + TSLM) / 2)

fc2 <- forecast(fit2, new_data = scenario) %>% 
  as_fable(response = "Number")

#Plot together both graphs to see the pattern
fc2 %>% autoplot(tslm, level=NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Bietschhorn") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare the scores of the models to find the best one
fc2 %>% accuracy(station) %>% arrange(RMSE)

```

#### **Blancherie Station**

```{r}
# Parameters for this station
station <- blancherie_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Blancherie") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the blancherie? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Blancherie
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Blancherie") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,2] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Blancherie' = '.mean')
```

#### **Agasse Station**

```{r}
# Parameters for this station
station <- agasse_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Agasse") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Agasse? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Agasse
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Agasse") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,3] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Agasse' = '.mean')
```

#### **Bramois Station**

```{r}
# Parameters for this station
station <- bramois_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bramois") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Bramois? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Agasse
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Bramois") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,4] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Bramois' = '.mean')
```

#### **Campus Station**

```{r}
# Parameters for this station
station <- campus_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Campus") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Bramois? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Agasse
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Campus") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ trend() + Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,5] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Campus' = '.mean')
```

#### **Cible Station**

```{r}
# Parameters for this station
station <- cible_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Cible") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Cible? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Cible
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Cible") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,6] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Cible' = '.mean')
```

#### **CRR Station**

```{r}
# Parameters for this station
station <- crr_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - CRR") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the CRR? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Cible
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Cible") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,7] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('CRR' = '.mean')
```

#### **Furet Station**

```{r}
# Parameters for this station
station <- furet_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Furet") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Furet? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Furet
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Furet") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,8] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Furet' = '.mean')
```

#### **GSD Station**

```{r}
# Parameters for this station
station <- gsd_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - GSD") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the GSD? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in GSD
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - GSD") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,9] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('GSD' = '.mean')
```

#### **GSN Station**

```{r}
# Parameters for this station
station <- gsn_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - GSN") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the GSN? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in GSD
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - GSN") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,10] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('GSN' = '.mean')
```

#### **Planta Station**

```{r}
# Parameters for this station
station <- planta_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Planta") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Planta? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Planta
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Planta") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,11] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Planta' = '.mean')
```

#### **Platta Station**

```{r}
# Parameters for this station
station <- platta_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Platta") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Platta? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Platta
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Platta") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,12] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Platta' = '.mean')
```

#### **PRP Station**

```{r}
# Parameters for this station
station <- prp_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - PRP") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the PRP? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in PRP
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - PRP") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,13] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('PRP' = '.mean')
```

#### **Scex Station**

```{r}
# Parameters for this station
station <- scex_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Scex") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Scex? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Scex
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Scex") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,14] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Scex' = '.mean')
```

#### **Stade Station**

```{r}
# Parameters for this station
station <- stade_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Stade") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Stade? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Stade
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Stade") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,15] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Stade' = '.mean')
```

#### **Stand Station**

```{r}
# Parameters for this station
station <- stand_wednesdays_bikes
station <- station[-c(1:54),] %>% 
  mutate(t = row_number())
```

```{r, message=FALSE, warning=FALSE}
### Time series for Wednesdays - Bikes ###

# Plot the time series for every wednesdays
station %>% 
  autoplot(Number) +
  geom_vline(xintercept=seq(0, interval, 144), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Stand") +
  labs(x = "Time [10']",
       y = "Number of bikes available")
```

```{r}
# Is it white noise for the bike at the Stand? 
station %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
station %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.
```

```{r, message=FALSE, warning=FALSE}
############################################################################################
                                      ###  Forecasts  ###
############################################################################################

# Forecast for bikes in Stand
fit <- station %>%
  filter(as_date(date) < as_date(day_forecasted)) %>% 
  model(ETS = ETS(Number),
        ARIMA = ARIMA(Number),
        NAIVE = NAIVE(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(station, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Forecast bikes - Stand") +
  labs(x = "Time [10']",
       y = "Number") 

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(station) %>% arrange(RMSE)


###################################   Linear Regression   ###############################

# Prepare data for Forecast
tslm <- station %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

######## Build the model for Bike #######

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bikes <- tslm_forecast %>% 
  model(TSLM = TSLM(Number ~ season() + Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bikes, new_data = scenario) %>% 
  as_fable(response = "Number")

fc %>% autoplot(station, level = NULL)

# Look at the Coefficients and Residuals
report(tslm_model_bikes)
tslm_model_bikes %>% gg_tsresiduals()

fc %>% accuracy(station) %>% arrange(RMSE)

forecast_final[,16] <- subset(fc, select = .mean)
forecast_final <- forecast_final %>% 
  rename('Stand' = '.mean')
```