#### **Gare de Sion Sud (GSD) Station**

```{r message=FALSE, warning=FALSE, include=FALSE}
# Creation of time series
GSD <- as_tsibble(GSD)
weekday <- weekdays(GSD$date)
GSD$weekday <- weekday # Get the weekday values
GSD$time <- as.POSIXct(GSD$date, format = "%H:%M:%S %p")
GSD$time <- as.numeric(GSD$date) #convert date values to numeric
as.numeric(GSD$time)

gsd <- GSD %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
gsd$minutes <- as.numeric(as.character(gsd$minutes))/60 # transform to minutes

# Filter the data by time difference of 10 min
gsd <- gsd %>% filter(minutes == 10) %>%
  select(-time,-name) %>%
  relocate(date, .before = Bike)

# Identifying the gaps on the ts and fill them
gsd.gaps <- has_gaps(gsd)
gsd.gaps <- scan_gaps(gsd)
gsd <- gsd %>% 
  fill_gaps(.full = TRUE) 

# Replace NA's values as previous row 
gsd_ts <- gsd %>%
  fill(Bike, `E-Bike`, Capacity, weekday, minutes)
scan_gaps(gsd_ts) # no missing values

#  convert our data frame from wide to long format.
gsd <- gsd_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)
```

```{r, message=FALSE, warning=FALSE}
# Parameters
end_time_series = 1206

### Usage for Wednesdays - Bikes ###
gsd_wednesday <- gsd %>%
  filter(weekday == "Wednesday") 
lubridate::day(gsd_wednesday$date) <- 16
lubridate::month(gsd_wednesday$date) <- 04
gsd_wednesday <- gsd_wednesday %>%
  group_by(date, Types) %>%
  summarise(Number = median(Number)) %>%
  as_tsibble(key = Types) %>%
  mutate(weekday = "Wednesday")
gsd_wednesday$Number <- ceiling(gsd_wednesday$Number)

gsd_wednesday %>% 
  select(-weekday) %>%
  autoplot(Number) +
  labs(x = "Time [10']",
       y = "Number") + 
  ggtitle("Wednesdays Usage(Mdn) - Gare de Sion Sud")


# Time series for Wednesdays - Bike
gsd_wednesdays_bike <- gsd %>% 
  filter(Types == "Bike" & weekday == "Wednesday") %>% 
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p1 <- gsd_wednesdays_bike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(seq(54,end_time_series,144)), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bike - Gare de Sion Sud") +
  labs(x = "Time [10']",
       y = "Number")

# Time series for Wednesdays - E-Bike
gsd_wednesdays_ebike <- gsd %>% 
  filter(Types == "E-Bike" & weekday == "Wednesday") %>% 
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p2 <- gsd_wednesdays_ebike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(seq(54,end_time_series,144)), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - E-Bike - Gare de Sion Sud") +
  labs(x = "Time [10']",
       y = "Number")

p1 / p2
```

```{r message=FALSE, echo = FALSE, warning=FALSE, results = 'hide'}
# Is it white noise for the bike at the gsd? 
p1 <- gsd_wednesdays_bike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? We confirm it with the test
gsd_wednesdays_bike %>% features(Number, unitroot_kpss) 

# Is our time series stationary or not? We confirm it with the test
gsd_wednesdays_ebike %>% features(Number, unitroot_kpss) 

# Is it white noise for the bike at the gsd?
p2 <- gsd_wednesdays_ebike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("E-Bike")
```

#### Forecasting ####

```{r}
## BIKE ##

# Parameters for the forecast
day_forecasted = '2022-05-04'
station = gsd_wednesdays_bike

gsd_wednesdays_bike_fc <- station %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Model with ETS and ARIMA
fit <- gsd_wednesdays_bike_fc %>%
  model(NAIVE = NAIVE(Number),
        ETS = ETS(Number),
        ARIMA = ARIMA(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(gsd_wednesdays_bike_fc, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Wednesday Forecast - Bike - Gare du Sud") +
  labs(x = "Time [10']",
       y = "Number") 

station %>% 
  filter(as_date(date) <= as_date(day_forecasted)) %>% 
  autoplot(Number)

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(gsd_wednesdays_bike) %>% arrange(RMSE)
```

```{r}
### Linear regression TSLM ###

# Parameters
station_ts = gsd_ts

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

# TSLM time series to get the weather data
tslm <- gsd_ts %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bike <- tslm_forecast %>% 
  model(TSLM = TSLM(Bike ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bike, new_data = scenario) %>% 
  as_fable(response = "Bike")

fc$test <- round(fc$Bike)

  tslm_forecast %>% 
  autoplot(Bike) +
  autolayer(fc, level = 0)

tslm %>% 
  filter(as_date(date) <= as_date(day_forecasted)) %>% 
  autoplot(Bike)
```

