#### **Gare de Sion Nord (GSN) Station**

```{r message=FALSE, warning=FALSE, include=FALSE}
# Creation of time series
GSN <- as_tsibble(GSN)
weekday <- weekdays(GSN$date)
GSN$weekday <- weekday # Get the weekday values
GSN$time <- as.POSIXct(GSN$date, format = "%H:%M:%S %p")
GSN$time <- as.numeric(GSN$date) #convert date values to numeric
as.numeric(GSN$time)

gsn <- GSN %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
gsn$minutes <- as.numeric(as.character(gsn$minutes))/60 # transform to minutes

# Filter the data by time difference of 10 min
gsn <- gsn %>% filter(minutes == 10) %>%
  select(-time,-name) %>%
  relocate(date, .before = Bike)

# Identifying the gaps on the ts and fill them
gsn.gaps <- has_gaps(gsn)
gsn.gaps <- scan_gaps(gsn)
gsn <- gsn %>% 
  fill_gaps(.full = TRUE) 

# Replace NA's values as previous row 
gsn_ts <- gsn %>%
  fill(Bike, `E-Bike`, Capacity, weekday, minutes)
scan_gaps(gsn_ts) # no missing values

#  convert our data frame from wide to long format.
gsn <- gsn_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)
```

```{r, message=FALSE, warning=FALSE}
### Usage for Wednesdays - Bikes ###
gsn_wednesday <- gsn %>%
  filter(weekday == "Wednesday") 
lubridate::day(gsn_wednesday$date) <- 16
lubridate::month(gsn_wednesday$date) <- 04
gsn_wednesday <- gsn_wednesday %>%
  group_by(date, Types) %>%
  summarise(Number = median(Number)) %>%
  as_tsibble(key = Types) %>%
  mutate(weekday = "Wednesday")
gsn_wednesday$Number <- ceiling(gsn_wednesday$Number)

gsn_wednesday %>% 
  select(-weekday) %>%
  autoplot(Number) +
  labs(x = "Time [10']",
       y = "Number") + 
  ggtitle("Wednesdays Usage(Mdn) - Gare de Sion Nord")


# Time series for Wednesdays - Bike
gsn_wednesdays_bike <- gsn %>% 
  filter(Types == "Bike" ) %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p1 <- gsn_wednesdays_bike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bike - Gare de Sion Nord") +
  labs(x = "Time [10']",
       y = "Number")

# Time series for Wednesdays - E-Bike
gsn_wednesdays_ebike <- gsn %>% 
  filter(Types == "E-Bike") %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p2 <- gsn_wednesdays_ebike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - E-Bike - Gare de Sion Nord") +
  labs(x = "Time [10']",
       y = "Number")

p1 / p2
```

The E-Bike after lag 50 show some patterns of white noise, but we can discard stationary because the test rejects the null hypothesis

```{r message=FALSE, warning=FALSE}
# Is it white noise for the bike at the gsn? 
p1 <- gsn_wednesdays_bike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
gsn_wednesdays_bike %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.

# Is our time series stationary or not? #We confirm it with the test
gsn_wednesdays_ebike %>% features(Number, unitroot_kpss) # No p-value < 0.05

# Is it white noise for the bike at the gsn?
p2 <- gsn_wednesdays_ebike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("E-Bike")
p1 / p2
```

#### Forecasting ####

```{r}
## BIKE ##

# Parameters for the forecast
day_forecasted = '2022-05-04'
station = gsn_wednesdays_bike

gsd_wednesdays_bike_fc <- station %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Model with ETS and ARIMA
fit <- gsd_wednesdays_bike_fc %>%
  model(NAIVE = NAIVE(Number),
        ETS = ETS(Number),
        ARIMA = ARIMA(Number)) %>%
  mutate(Combination = (ETS + ARIMA + NAIVE) / 3)

fc <- fit %>% forecast(h = 144)

fc %>% autoplot(gsd_wednesdays_bike_fc, level = NULL) +
  guides(colour=guide_legend(title = "Models")) +
  ggtitle("Wednesday Forecast - Bike - Bietschhorn") +
  labs(x = "Time [10']",
       y = "Number") 

station %>% 
  filter(as_date(date) <= as_date(day_forecasted)) %>% 
  autoplot(Number)

# Compare models and arrange by RMSE to select the best
fc %>% accuracy(gsd_wednesdays_bike_fc) %>% arrange(RMSE)
```

```{r}
### Linear regression TSLM ###

# Parameters
station_ts = gsn_ts

# Keep only weather information for this time
weather_scenario <- weather_data %>% 
  filter(as_date(date) == as_date(day_forecasted))

# TSLM time series to get the weather data
tslm <- station_ts %>%
  dplyr::left_join(weather_data, by = "date") %>%
  na.omit() %>%
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

# TSLM_forecast
tslm_forecast <- tslm %>% 
  filter(as_date(date) < as_date(day_forecasted))

# Create a scenario based on the inputs of weather
scenario <- new_data(tslm_forecast, n = 144) %>% 
  mutate(Air_Temperature=weather_scenario$Air_Temperature,
         Precipitation=weather_scenario$Precipitation,
         Virtual_Temperature=weather_scenario$Virtual_Temperature,
         Wind_Speed=weather_scenario$Wind_Speed)

# TSLM model
tslm_model_bike <- tslm_forecast %>% 
  model(TSLM = TSLM(Bike ~ Air_Temperature + Precipitation +
                      Virtual_Temperature + Wind_Speed))

fc <- forecast(tslm_model_bike, new_data = scenario) %>% 
  as_fable(response = "Bike")

tslm_forecast %>% 
  autoplot(Bike) +
  autolayer(fc, level = 0)

tslm %>% 
  filter(as_date(date) <= as_date(day_forecasted)) %>% 
  autoplot(Bike)
```
