#### **Ancien Stand Station**

```{r message=FALSE, warning=FALSE, include=FALSE}
# Creation of time series
Stand <- as_tsibble(Stand)
weekday <- weekdays(Stand$date)
Stand$weekday <- weekday # Get the weekday values
Stand$time <- as.POSIXct(Stand$date, format = "%H:%M:%S %p")
Stand$time <- as.numeric(Stand$date) #convert date values to numeric
as.numeric(Stand$time)

stand <- Stand %>% 
  mutate(minutes = time - lag(time, default = first(time))) # subtract days
stand$minutes <- as.numeric(as.character(stand$minutes))/60 # transform to minutes

# Filter the data by time difference of 10 min
stand <- stand %>% filter(minutes == 10) %>%
  select(-time,-name) %>%
  relocate(date, .before = Bike)

# Identifying the gaps on the ts and fill them
stand.gaps <- has_gaps(stand)
stand.gaps <- scan_gaps(stand)
stand <- stand %>% 
  fill_gaps(.full = TRUE) 

# Replace NA's values as previous row 
stand_ts <- stand %>%
  fill(Bike, `E-Bike`, Capacity, weekday, minutes)
scan_gaps(stand_ts) # no missing values

#  convert our data frame from wide to long format.
stand <- stand_ts %>% 
  gather("Bike", "E-Bike", "Capacity", key = Types, value = Number) %>%
  relocate(Types, .before = weekday) %>%
  relocate(Number, .before = weekday)
```

```{r, message=FALSE, warning=FALSE}
### Usage for Wednesdays - Bikes ###
stand_wednesday <- stand %>%
  filter(weekday == "Wednesday") 
lubridate::day(stand_wednesday$date) <- 16
lubridate::month(stand_wednesday$date) <- 04
stand_wednesday <- stand_wednesday %>%
  group_by(date, Types) %>%
  summarise(Number = median(Number)) %>%
  as_tsibble(key = Types) %>%
  mutate(weekday = "Wednesday")
stand_wednesday$Number <- ceiling(stand_wednesday$Number)

stand_wednesday %>% 
  select(-weekday) %>%
  autoplot(Number) +
  labs(x = "Time [10']",
       y = "Number") + 
  ggtitle("Wednesdays Usage(Mdn) - Stand")


# Time series for Wednesdays - Bike
stand_wednesdays_bike <- stand %>% 
  filter(Types == "Bike" ) %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p1 <- stand_wednesdays_bike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - Bike - Stand") +
  labs(x = "Time [10']",
       y = "Number")

# Time series for Wednesdays - E-Bike
stand_wednesdays_ebike <- stand %>% 
  filter(Types == "E-Bike") %>% 
  filter(weekday == "Wednesday") %>%
  mutate(t = row_number()) %>% 
  update_tsibble(index = t, regular = TRUE)

p2 <- stand_wednesdays_ebike %>% 
  autoplot(Number) +
  geom_vline(xintercept=c(54,198,342,486,630,774,918,1062), linetype="dotted") + #Per day
  ggtitle("Wednesdays time series - E-Bike - Stand") +
  labs(x = "Time [10']",
       y = "Number")

p1 / p2
```

```{r message=FALSE, warning=FALSE}
# Is it white noise for the bike at the stand? 
p1 <- stand_wednesdays_bike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("Bike")

# Is our time series stationary or not? #We confirm it with the test
stand_wednesdays_bike %>% features(Number, unitroot_kpss) 

#The p-value of 0.01 indicates strong evidence to 
#reject the null hypothesis of stationarity.

# Is our time series stationary or not? #We confirm it with the test
stand_wednesdays_ebike %>% features(Number, unitroot_kpss) # No p-value < 0.05

# Is it white noise for the bike at the stand?
p2 <- stand_wednesdays_ebike %>% 
  ACF(Number, lag_max = 144) %>% 
  autoplot() +  ggtitle("E-Bike")
p1 / p2
```


### **Sion Stations**

```{r message=FALSE, warning=FALSE, include=FALSE}
# Create a New master table for all the stations with the Median usage per station

############ Prepare data ################

bietschhorn_bike <- bietschhorn_wednesday %>%
  spread(Types, Number) %>%
  rename(Bietschhorn = Bike) %>%
  select(date, Bietschhorn)
bietschhorn_ebike <- bietschhorn_wednesday %>%
  spread(Types, Number) %>%
  rename(Bietschhorn = `E-Bike`) %>%
  select(date, Bietschhorn)

blancherie_bike <- blancherie_wednesday %>%
  spread(Types, Number) %>%
  rename(Blancherie = Bike) %>%
  select(date, Blancherie)
blancherie_ebike <- blancherie_wednesday %>%
  spread(Types, Number) %>%
  rename(Blancherie = `E-Bike`) %>%
  select(date, Blancherie)

cible_bike <- cible_wednesday %>%
  spread(Types, Number) %>%
  rename(Cible = Bike) %>%
  select(date, Cible)
cible_ebike <- cible_wednesday %>%
  spread(Types, Number) %>%
  rename(Cible = `E-Bike`) %>%
  select(date, Cible)

gsd_bike <- gsd_wednesday %>%
  spread(Types, Number) %>%
  rename(GSD = Bike) %>%
  select(date, GSD)
gsd_ebike <- gsd_wednesday %>%
  spread(Types, Number) %>%
  rename(GSD = `E-Bike`) %>%
  select(date, GSD)


prp_bike <- prp_wednesday %>%
  spread(Types, Number) %>%
  rename(PRP = Bike) %>%
  select(date, PRP)
prp_ebike <- prp_wednesday %>%
  spread(Types, Number) %>%
  rename(PRP = `E-Bike`) %>%
  select(date, PRP)


platta_bike <- platta_wednesday %>%
  spread(Types, Number) %>%
  rename(Platta = Bike) %>%
  select(date, Platta)
platta_ebike <- platta_wednesday %>%
  spread(Types, Number) %>%
  rename(Platta = `E-Bike`) %>%
  select(date, Platta)


planta_bike <- planta_wednesday %>%
  spread(Types, Number) %>%
  rename(Planta = Bike) %>%
  select(date, Planta)
planta_ebike <- planta_wednesday %>%
  spread(Types, Number) %>%
  rename(Planta = `E-Bike`) %>%
  select(date, Planta)


crr_bike <- crr_wednesday %>%
  spread(Types, Number) %>%
  rename(CRR = Bike) %>%
  select(date, CRR)
crr_ebike <- crr_wednesday %>%
  spread(Types, Number) %>%
  rename(CRR = `E-Bike`) %>%
  select(date, CRR)


campus_bike <- campus_wednesday %>%
  spread(Types, Number) %>%
  rename(Campus = Bike) %>%
  select(date, Campus)
campus_ebike <- campus_wednesday %>%
  spread(Types, Number) %>%
  rename(Campus = `E-Bike`) %>%
  select(date, Campus)


scex_bike <- scex_wednesday %>%
  spread(Types, Number) %>%
  rename(Scex = Bike) %>%
  select(date, Scex)
scex_ebike <- scex_wednesday %>%
  spread(Types, Number) %>%
  rename(Scex = `E-Bike`) %>%
  select(date, Scex)


furet_bike <- furet_wednesday %>%
  spread(Types, Number) %>%
  rename(Furet = Bike) %>%
  select(date, Furet)
furet_ebike <- furet_wednesday %>%
  spread(Types, Number) %>%
  rename(Furet = `E-Bike`) %>%
  select(date, Furet)


agasse_bike <- agasse_wednesday %>%
  spread(Types, Number) %>%
  rename(Agasse = Bike) %>%
  select(date, Agasse)
agasse_ebike <- agasse_wednesday %>%
  spread(Types, Number) %>%
  rename(Agasse = `E-Bike`) %>%
  select(date, Agasse)


stade_bike <- stade_wednesday %>%
  spread(Types, Number) %>%
  rename(Stade = Bike) %>%
  select(date, Stade)
stade_ebike <- stade_wednesday %>%
  spread(Types, Number) %>%
  rename(Stade = `E-Bike`) %>%
  select(date, Stade)


gsn_bike <- gsn_wednesday %>%
  spread(Types, Number) %>%
  rename(GSN = Bike) %>%
  select(date, GSN)
gsn_ebike <- gsn_wednesday %>%
  spread(Types, Number) %>%
  rename(GSN = `E-Bike`) %>%
  select(date, GSN)


stand_bike <- stand_wednesday %>%
  spread(Types, Number) %>%
  rename(Stand = Bike) %>%
  select(date, Stand)
stand_ebike <- stand_wednesday %>%
  spread(Types, Number) %>%
  rename(Stand = `E-Bike`) %>%
  select(date, Stand)


bramois_bike <- bramois_wednesday %>%
  spread(Types, Number) %>%
  rename(Bramois = Bike) %>%
  select(date, Bramois)
bramois_ebike <- bramois_wednesday %>%
  spread(Types, Number) %>%
  rename(Bramois = `E-Bike`) %>%
  select(date, Bramois)

################# Create Master tables #####################

library(purrr)
sion_bike <- list(bietschhorn_bike, blancherie_bike, cible_bike, gsd_bike, prp_bike, 
                platta_bike, planta_bike, crr_bike, campus_bike, scex_bike, furet_bike,
                agasse_bike, stade_bike, gsn_bike, stand_bike, bramois_bike) %>%
  reduce(dplyr::left_join, by= "date")

sion_ebike <- list(bietschhorn_ebike, blancherie_ebike, cible_ebike, gsd_ebike, 
                  prp_ebike, platta_ebike, planta_ebike, crr_ebike, campus_ebike,
                  scex_ebike, furet_ebike, agasse_ebike, stade_ebike, gsn_ebike,
                  stand_ebike, bramois_ebike) %>%
  reduce(dplyr::left_join, by= "date")

# Convert ts to tsibble and pivot to long format
sion_bike_long <- sion_bike %>%   
  gather("Bietschhorn", "Blancherie", "Cible", "GSD", "PRP", "Platta", "Planta",
         "CRR", "Campus", "Scex", "Furet", "Agasse", "Stade", "GSN", "Stand",
         "Bramois", key = Stations, value = Number)

sion_ebike_long <- sion_ebike %>%   
  gather("Bietschhorn", "Blancherie", "Cible", "GSD", "PRP", "Platta", "Planta",
         "CRR", "Campus", "Scex", "Furet", "Agasse", "Stade", "GSN", "Stand",
         "Bramois", key = Stations, value = Number)

```


```{r, echo=FALSE, message=FALSE}
########### Plot Them ################

sion_bike_long %>% autoplot(Number) + ylab("Number of Bikes") +
  facet_wrap(vars(Stations), scales = "free_y", ncol = 4) + 
  theme(legend.position = "none") + guides(x =  guide_axis(angle = 20)) +
  labs(x = "Time [10']",
       y = "Number") +
  ggtitle("Wednesdays Usage(Mdn) - Bike - Sion Stations")

sion_ebike_long %>% autoplot(Number) + ylab("Number of Bikes") +
  facet_wrap(vars(Stations), scales = "free_y", ncol = 4) + 
  theme(legend.position = "none") + guides(x =  guide_axis(angle = 20)) +
  labs(x = "Time [10']",
       y = "Number") +
  ggtitle("Wednesdays Usage(Mdn) - E-Bike - Sion Stations")
```
